# 운영환경용 설정 템플릿
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

logging:
  level:
    com.minicarrot.product: INFO
    org.springframework.web: WARN
    root: WARN 